version: '2'
services:
  protochannel:
    build: .
    environment:
      - WS_URI=https://ropsten.infura.io
      - DB_DSN=host=postgres user=f3b1be969686afb4520ce dbname=protochannel sslmode=disable password=839169c0ea5e59146a
      - PRIVATE_KEY=8e973e8e3d06a321d7285695560a45bd4946eb6f59410732b048c59a0174cc09 # 0xcd5bb3a1E6d7676DAD570566A455dC38b7e3EaDf
      - CONTRACT_ADDRESS=0xcd5bb3a1E6d7676DAD570566A455dC38b7e3EaDf #todo deploy
      - RETRY=3
    links:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=f3b1be969686afb4520ce
      - POSTGRES_PASSWORD=839169c0ea5e59146a
      - POSTGRES_DB=protochannel

  caddy-rev:
    image: abiosoft/caddy
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - "./Caddyfile:/etc/Caddyfile:ro"
      - "./html:/var/www:ro"
    links:
      - protochannel
