// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// StatusHandlerFunc turns a function with the right signature into a status handler
type StatusHandlerFunc func(StatusParams) middleware.Responder

// Handle executing the request and returning a response
func (fn StatusHandlerFunc) Handle(params StatusParams) middleware.Responder {
	return fn(params)
}

// StatusHandler interface for that can handle valid status params
type StatusHandler interface {
	Handle(StatusParams) middleware.Responder
}

// NewStatus creates a new http.Handler for the status operation
func NewStatus(ctx *middleware.Context, handler StatusHandler) *Status {
	return &Status{Context: ctx, Handler: handler}
}

/*Status swagger:route GET /status status

Various information on the micro service

Return various information

*/
type Status struct {
	Context *middleware.Context
	Handler StatusHandler
}

func (o *Status) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewStatusParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
