// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"context"
	"crypto/tls"
	"net/http"
	"time"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	swag "github.com/go-openapi/swag"
	graceful "github.com/tylerb/graceful"

	"github.com/Magicking/protochannel/internal"
	"github.com/Magicking/protochannel/restapi/operations"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../docs/protochannel.yml

var ethopts struct {
	WsURI        string `long:"ws-uri" env:"WS_URI" description:"Ethereum WS URI (e.g: ws://HOST:8546)"`
	Retry        int    `long:"retry" env:"RETRY" description:"Max connection retry"`
	ContractAddr string `long:"contract-address" env:"CONTRACT_ADDRESS" description:"Deployed contract address"`
	PrivateKey   string `long:"pkey" env:"PRIVATE_KEY" description:"hex encoded private key"`
}

var serviceopts struct {
	SchedulerTick int    `long:"sched-tick" env:"SCHED_TICK" default:"10" description:"Internal Scheduler ticker in second"`
	DbDSN         string `long:"db-dsn" env:"DB_DSN" description:"Database DSN (e.g: /tmp/test.sqlite)"`
}

func configureFlags(api *operations.ProtochannelAPI) {
	ethOpts := swag.CommandLineOptionsGroup{
		LongDescription:  "",
		ShortDescription: "Ethereum options",
		Options:          &ethopts,
	}
	serviceOpts := swag.CommandLineOptionsGroup{
		LongDescription:  "",
		ShortDescription: "Service options",
		Options:          &serviceopts,
	}
	api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ethOpts, serviceOpts}
}

func configureAPI(api *operations.ProtochannelAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//.Background()
	// Example:
	// api.Logger = log.Printf

	ctx := internal.InitContext(context.Background())
	internal.NewSchedulerToContext(ctx, time.Duration(serviceopts.SchedulerTick)*time.Second)
	internal.NewDBToContext(ctx, serviceopts.DbDSN)
	internal.NewCCToContext(ctx, ethopts.WsURI, ethopts.Retry)
	//internal.NewBLKToContext(ctx, ethopts.WsURI, ethopts.Retry)
	internal.Init(ctx, ethopts.ContractAddr, ethopts.PrivateKey)

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.CommitToChannelHandler = operations.CommitToChannelHandlerFunc(func(params operations.CommitToChannelParams) middleware.Responder {
		return internal.CommitToChannel(ctx, params)
	})
	api.StatusHandler = operations.StatusHandlerFunc(func(params operations.StatusParams) middleware.Responder {
		return middleware.NotImplemented("operation .Status has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
