// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Information information
// swagger:model Information
type Information struct {

	// Contract ABI JSON encoded
	Abi string `json:"abi,omitempty"`

	// channels
	Channels InformationChannels `json:"channels"`

	// Channel address
	ContractAddress string `json:"contract_address,omitempty"`
}

// Validate validates this information
func (m *Information) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Information) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Information) UnmarshalBinary(b []byte) error {
	var res Information
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
